name: Test Build GHRC Workflow

on:
    workflow_dispatch:
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    MONGO_URI: ${{ vars.MONGO_URI }}
    MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    docker:
        name: docker image build
        runs-on: ubuntu-latest
        steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Login To GHRC
          uses: docker/login-action@v3
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: GHRC Meta Data
          uses: docker/metadata-action@v5
          id: meta
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
        - name: Build And Push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
        
        - name: Generate artifact attestation
          uses: actions/attest-build-provenance@v1
          with:
            subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
            subject-digest: ${{ steps.push.outputs.digest }}
            push-to-registry: true
              
        
        # - name: Test Docker Image
        #   run: |
        #     docker images
        #     docker run --name solar-system-app -d \
        #         -p 3000:3000 \
        #         -e MONGO_URI=$MONGO_URI \
        #         -e MONGO_USERNAME=$MONGO_USERNAME \
        #         -e MONGO_PASSWORD=$MONGO_PASSWORD \
        #         
            
        #     echo Testing Image URL using wget
        #     wget -q -O - 127.0.0.1:3000/live | grep live